### ISSUE TITLE
Cannot communicate with backend - no JWT to send

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#100]
The backend now enforces JWT Auth, however login has not yet been implemented.

Requires:
~#29~ #85  
#58 
#48

**Comment by FJMentz** [comment]
#29 is marked as duplicate and closed? Can you please reference the 'duplicated' one @egeldenhuys .

**Comment by egeldenhuys** [comment]
Sorry that should probably have been #85 instead of #29

**Comment by egeldenhuys** [comment]
We now have a login page
