### ISSUE TITLE
Service card view duplicates tasks

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#102]
#### Steps to reproduce the issue

1.  Navigate to services card view
2. Click on service card
3. Close card
3. Click on same card again

#### What's the expected result?
- The tasks displayed do not change unless the scale has also changed

#### What's the actual result?
- Tasks associated with the service are duplicated in the view

#### Additional details / screenshot

- ![screen shot 2018-05-12 at 14 34 30](https://user-images.githubusercontent.com/5778739/39957351-d2cfafcc-55f1-11e8-8dee-f2a13fc7652a.png)

**Comment by FJMentz** [comment]
@egeldenhuys Ahh, had the same issue with other views

**Comment by CDuPlooy** [comment]
This is due to  services being pushed to an initially empty array instead of assigning the returned array.

EDIT:
might 😆

**Comment by FJMentz** [comment]
@CDuPlooy , Tis indeed the reason 😉
