### ISSUE TITLE
Volumes card view inconsistent width

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#104]
If this is an intended feature then let me know and close the issue :wink: 

#### Steps to reproduce the issue

1.  Visit Volume Card View with volumes that have long and short mount points

#### What's the expected result?
- Text fields that are too long are ellipsized or wrapped so that one card does not take up the entire width of the screen

#### What's the actual result?
- Cards are as wide as the text in them, creating irregular card layout.

#### Additional details / screenshot
-  ![volume_card_width](https://user-images.githubusercontent.com/5778739/39957574-915b45e8-55f5-11e8-92cf-4574ee87a15c.png)

**Comment by FJMentz** [comment]
@egeldenhuys, ui was basically just made to be a 'dont-break' prototype for the demo, everything still needs to be finished.

**Comment by egeldenhuys** [comment]
Just enumerating the bugs as I find them in master to keep the surprises to a minimum
