### ISSUE TITLE
Services Pages

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#119]
- [ ] 1. Add a page for create service
- [ ] 2. Create page to inspect service, view its tasks (docker ps), detail, etc.
- [ ] 3. Create update page
- [ ] 4. Link to Stack page (compose operation)
- [ ] 5. Look at redeploying the service
- [ ] 6. Look into how logs will be displayed and implement it 
- [x] 7. Add filter to list-view page
- [ ] 8. Change column names according to what Compiax wants
- [ ] 9. Test operations

Operations:
- [x] 1. getServices
- [x] 2. inspectServices
- [x] 3. deleteServices
- [x] 4. getServiceLog => Doesn't display very nicely
- [ ] 5. updateServices
- [ ] 6. scaleServices
- [ ] 7. createServices

**Comment by egeldenhuys** [comment]
For now we will focus on the Stack create and edit page as it provides the same ability as the stack pages but with less work (just need to reverse docker inspect to create a docker compose file)
