### ISSUE TITLE
Stop container

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#12]
Button on each card (container) that allows the user to stop the container?

Should somehow not be on docks or docks-ui containers? (maybe add this constraint only later as this is the only containers we have running during the demo?)

**Comment by FJMentz** [comment]
Start and stop container seems to work now. Just has a small delay when stopping. Might want to look into this?

**Comment by CDuPlooy** [comment]
The delay is due to the backend, cleanup being done by docker engine. I suggest adding a toast notification to just notify the user that something is happening. Maybe some animation.

**Comment by FJMentz** [comment]
This has been closed by pull #19 (i think)
