### ISSUE TITLE
Remove Mock Services

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#120]
We need to start move away from the mock Service and test it with our services. This should be implemented by Demo 4.

**Comment by annamarieHelberg** [comment]
@CDuPlooy can we please start looking into this. The majority of functions have been implemented but can we please start testing it with real data to see if they work?

**Comment by CDuPlooy** [comment]
Sounds good ^^

**Comment by CDuPlooy** [comment]
So just an update on this. And a few questions ^^ This seems related to #111. Are we focusing on integration testing or specifically the removal of the mock service? Those might seem to go hand in hand but I don't think they should. 

The idea behind the mock service was that it be used when something in the api fails during a demo - hope for the best but plan for the worst and all that. Personally I think we should keep the mock service and create ( or well mock ) functions that return dummy values for the off chance that something goes wrong during the demos; I'm not overly fond of how it is currently structured but lets decide on whether to keep or remove it first.  

I'd like to just give a small example to illustrate my point. 

In the previous demo we had a problem with the creation of stacks not being supported by the docker api. While @devosray created a work around for us another solution could have been to use the mock service to illustrate what we are trying to achieve.

**Comment by egeldenhuys** [comment]
Mock services are useful when the back-end is not yet capable of providing the data. This allows the front-end to be implemented and tested and then without hassle switch over to using live data from the back-end.

As with the example given above, it allows us to demonstrate functionality that is not yet supported by the back-end.

However from a Continuous Deployment perspective I prefer to only work with live data

**Comment by annamarieHelberg** [comment]
I agree with you @CDuPlooy  that it is helpful but we have no idea whether the actual functions really work. Also, this is demo 4 so actually by now we shouldn't have any mock services anymore. If the backend doesn't support some functions yet it is quite a big concern and should be investigated.

**Comment by CDuPlooy** [comment]
I'm on mobile so I'm not going to use the @s right now x)

I'm currently working on proper tests in the testing branch. Most of my time has gone into researching though. I'll pm you what I have so far and we can start working on it. :)

**Comment by egeldenhuys** [comment]
All data is now live and the MockService is no longer being used
