### ISSUE TITLE
Task List and Card view broken

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#126]
Introduced by #116 

Console error
```
ERROR TypeError: "_v.context.$implicit.status is undefined"
...
View_TaskListViewComponent_1     task-list-view.component.html:9:24
```

![screen shot 2018-07-12 at 08 41 57](https://user-images.githubusercontent.com/5778739/42616695-7ec420be-85af-11e8-8c6c-2e0fdfcb46ad.png)
![screen shot 2018-07-12 at 08 42 01](https://user-images.githubusercontent.com/5778739/42616696-7f057a78-85af-11e8-8a1b-748c15b1828d.png)

**Comment by CDuPlooy** [comment]
Fixed by f020bd048dd52e825d975d506eafa3b01104cab9
