### ISSUE TITLE
Turning list view into a table

### ISSUE THREAD

**Issue by ghost** [TripleParity/docks-ui#128]
Currently I feel the view for the service and volume list view (I don't feel it matters to much with the task view) does not give the user enough information without them first clicking on the listed item to bring down what basically already resembles a table. Secondly the view currently is unintuitive and may result in the user never clicking the list revealing the replicas mode etc etc. Thirdly I feel the current view waste's a lot of space and can be made neater. 

I would like to propose this idea
![screenshot_2018-07-12 untitled drawing](https://user-images.githubusercontent.com/22499677/42638665-88229fb6-85ee-11e8-8e4c-357347621f75.png)
(I noticed I used the word edit instead of operations in the screen shot but it should be operations)

Reasons for using a table instead 

1. Using the same table idea that @egeldenhuys used for the "users" component, provides us with functionality such as search, limit the number of visible components on a page, sorting/ arrange by, etc etc
2. The overall appearance is better and less space is wasted 
3. it gives more experienced users of docker faster access to more relevant information than currently available.

**Comment by ghost** [comment]
Too view the image the we can make drop down like so
![screenshot_2018-07-12 untitled drawing 1](https://user-images.githubusercontent.com/22499677/42639672-e55a44fc-85f0-11e8-8328-15758ca67ce0.png)

**Comment by annamarieHelberg** [comment]
@Paulo-W we dicussed this issue in a meeting. We all decided on using the ngx-datatable for all the list views.

**Comment by ghost** [comment]
@annamarieHelberg  Yes thanks I remember I just wanted to document it since that was a long time ago and nothing has been done since

**Comment by annamarieHelberg** [comment]
This is linked to #123 . We need all the list views to be updated. This is why I closed this issue.
