### ISSUE TITLE
Volumes

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#147]
- [x] Volume List - `/volumes`
- [x] Volume Details - `/volumes/{volume_name}`
- [x] Create Volume - `/volumes/create`
- [x] Delete volume from detail page
----

#### Display
- Name
- Driver

#### Links
- New volume `/volumes/create`
- View volume `/volumes/{volume_name}`

#### Display
- Name
- Scope
- Mountpoint
- Driver information
- Linked Services
  - Name
  - Image
  - Replicas
  - Ports
  - Status

#### Actions
- Delete

#### Parameters
- Name
- Driver Name
- Driver Options
- Labels

**Comment by egeldenhuys** [comment]
Just need a delete button then the basic version will be complete

**Comment by ghost** [comment]
> Linked Services

 >   Name
 >   Image
 >   Replicas
 >  Ports
 >   Status


Is not available in the volume sent through. Also should I not display the labels of the volume in detail view as well?

**Comment by egeldenhuys** [comment]
An optimisation would be to add a API endpoint, to return service details given a volume ID.

Yes, please display labels as well

**Comment by egeldenhuys** [comment]
Implemented by #188
