### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#149]
#### Display
- Name
- Image
- Node
- Status

#### Links
- View Task details `/tasks/{task_id}`

#### Display
- ID
- Service
- Name
- Created
- Last Update
- Image
- Node
- Status
  - State
  - Desired State

**Comment by ghost** [comment]
Can I please start working on the detailed page view here, I feel once it has been set up in tasks we will be able to propagate it further onwards. Unless someone is already working on it?

**Comment by egeldenhuys** [comment]
@Paulo-W can you please create a prototype design and we can have a group discussion?
See #151

**Comment by egeldenhuys** [comment]
List view has been implemented, still need to do the detail view
