### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by CDuPlooy** [TripleParity/docks-ui#15]
Should we move components into a _components directory? We are already doing this for _services and _models so I feel we might as well.

**Comment by egeldenhuys** [comment]
What is reason behind the underscore convention?

**Comment by FJMentz** [comment]
It's a convention also used by Compiax (and I believe in the community of angular) to destinguish between something and something else... @CDuPlooy will probably be able to describe better but thats what it comes down to.
