### ISSUE TITLE
Detail View Style

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#151]
The style and layout for detail pages should be consistent.

Prototypes should be implemented in code to make it easy to start using.
Once a prototype has been made open a PR for discussion. Once approved the design can be implemented.

**Comment by ghost** [comment]
Will do :+1:

**Comment by ghost** [comment]
Some basic html ideas for each page have been implemented excluding ngx-dataTables in the services page and stack page. 
**Task Detail Page**
![image](https://user-images.githubusercontent.com/22499677/45186281-35c25200-b22d-11e8-9312-cf850050270b.png)

**Service Detail Page**
![image](https://user-images.githubusercontent.com/22499677/45186829-0d3b5780-b22f-11e8-9c81-3617ee44176b.png)

As stated the ngx-dataTables is not implemented yet. also if you are curious as to what is in the actions drop down. 
![image](https://user-images.githubusercontent.com/22499677/45186354-7b7f1a80-b22d-11e8-913e-7cb7064e9fd1.png)
Nice and neat keeps the view table smaller. 

**Stack Page**
![image](https://user-images.githubusercontent.com/22499677/45186392-9d789d00-b22d-11e8-967e-a652de53ffbe.png)
ngx-dataTables shows list of services

**Network Page**
![image](https://user-images.githubusercontent.com/22499677/45186453-c731c400-b22d-11e8-80bb-a039edc0a496.png)

**Volume Page** 
![image](https://user-images.githubusercontent.com/22499677/45186470-dadd2a80-b22d-11e8-9b73-34fce78f2f97.png)

Please have a look through each page and let me know what design feature you would like to change, remember these are only prototypes and still need to be implemented so sooner we can start that the better.

**Comment by egeldenhuys** [comment]
Looks very good!

For the **Service Detail Page**, we will work on teams as a last priority so the date created and updated can be moved to general and the Meta section removed.

Seeing as we will be using Services and Tasks datatables in two locations, I wonder if it will be worth making those shared components which accepts arguments. That way the tables can be included as one-liners in the HTML
