### ISSUE TITLE
Remove paging from datatables

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#167]
Since we are already fetching all the data it would be more convenient to display everything at once.

**Comment by ghost** [comment]
I'm not so sure, having a page that has 1000 elements on it will possibly slow performance, having less space for elements places more focus on the search bar and that is probably what the user is going to use any way. But I think we should have a vote on this please.

**Comment by CDuPlooy** [comment]
I'd also prefer not displaying everything on one page iff we can get the search working. Also possibly sort by state or something similar.

**Comment by egeldenhuys** [comment]
Maybe a sane limit such as 100 items would be better then? We can test the performance with more elements.

My reason for wanting to see more is often I want to get an overview of what is happening, without navigating table pages.

Sort and multi column searching would already help

**Comment by egeldenhuys** [comment]
Data tables has a 10k element demo that works fine, can't remember if it is one one page though
