### ISSUE TITLE
Stop or replace timer on Nodes page

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#172]
Currently each time the Nodes page is visited, another timer (`setInterval`) is started. The old timer is not stopped. This may cause problems for extended use.

Either we need to stop the timer when navigating away from the page, or stream docker events using the API.

**Comment by FJMentz** [comment]
So I might have found a possible solution [here](https://github.com/NativeScript/nativescript-angular/issues/1049). I'm note sure however if this will work in all cases.

**Comment by egeldenhuys** [comment]
That might work, thank you for finding that

**Comment by FJMentz** [comment]
I will try to implement and test this by tonight, just need to setup another computer to have more than one node in my development swarm.

**Comment by egeldenhuys** [comment]
Fixed by @CDuPlooy for another page, see his solution

**Comment by FJMentz** [comment]
Addressed along with #181 in commit [9254413](https://github.com/TripleParity/docks-ui/commit/9254413847fcd0b474e98f4f19d2f48f3e0b0ba3)
