### ISSUE TITLE
Stack Delete confirmation is missing stack name

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#173]
![naam](https://user-images.githubusercontent.com/5778739/46280040-2653d180-c56b-11e8-9134-6e84e1811ee0.png)

**Comment by FJMentz** [comment]
Will look into this.

**Comment by ghost** [comment]
Are we not going to implement a feature where the user has to type the name of the object they want to delete before it is deleted??

**Comment by egeldenhuys** [comment]
That would be a nice feature, but a low priority currently
