### ISSUE TITLE
Offset problem

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#193]
This might have been previously addressed, but while working I noticed a small offset problem of one of the elements. Please see image attached. @Paulo-W you're good at these things, will you please just check it out?

<img width="1680" alt="screen shot 2018-10-09 at 23 24 32" src="https://user-images.githubusercontent.com/17801831/46702487-93c6c880-cc23-11e8-891e-6f591b2033b4.png">

This was while viewing a log of a service.

**Comment by ghost** [comment]
Already fixed will make a new pull request for services update soon
