### ISSUE TITLE
Side navbar size difference 

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#196]
The navbar seems to change in size depending on the page you are on. I don't know if this has been addressed but I think if there is time we should fix this. Please and thank you.

**Comment by egeldenhuys** [comment]
With the scroll bar appearing? Or is it more severe?

**Comment by annamarieHelberg** [comment]
It is a very slight offset. It might be because of the scroll bar. That is why I said if we have time.

**Comment by egeldenhuys** [comment]
We will review this issue again later

**Comment by egeldenhuys** [comment]
Thank you for spotting this, I never noticed it until now!
