### ISSUE TITLE
Pictures in cards

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#27]
I would like to make a request to remove the pictures from the cards and rather show the status by an icon or a colour title or something like that.

I feel that this will make the cards smaller making it easier to scale the cards smaller to show more on a page.

**Comment by egeldenhuys** [comment]
What if we replace the cards with a table?

**Comment by annamarieHelberg** [comment]
I think we should have both a cards and table view as part of scalability.

**Comment by FJMentz** [comment]
I agree with @annamarieHelberg that having both will give the user a better overview of the system for different needs and functions.

**Comment by egeldenhuys** [comment]
No longer applicable - Containers are no longer part of the system.
