### ISSUE TITLE
Service List

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#35]
Summary of Services in swarm:
- [x] Name
- [ ] Stack
- [x] Image
- [x] Mode
- [x] Replicas
- [x] Published Ports
- [x] Last Update

**Comment by FJMentz** [comment]
@egeldenhuys, Can I make a suggestion to remove published ports here and only have it in the card view? At the moment it might just look a bit unappealing to some. If it's not too unappealing we can leave it as is.

Example below (fully expanded with only one port):
<img width="1113" alt="screen shot 2018-05-10 at 00 45 28" src="https://user-images.githubusercontent.com/17801831/39843471-772c90e8-53eb-11e8-8a18-d3dbf8e17811.png">

**Comment by egeldenhuys** [comment]
Card view only is fine :+1:
