### ISSUE TITLE
Service Detail

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#36]
- [x] ID
- [x] Name
- [ ] Stack
- [x] Image
- [x] Mode
- [x] Replicas
- [x] Published Ports
- [x] Created At
- [x] Last Update
- [ ] Volumes*
- [ ] Networks*
- [x] Tasks*

**Comment by FJMentz** [comment]
@egeldenhuys, can you maybe explain what you want for **Stack**, **Volumes** and **Networks**?

**Comment by egeldenhuys** [comment]
For Stack, it needs to show the name, or a link to the stack the service is optionally part of.

Volumes - Display the volumes that are attached to the service. From `docker inspect service {id}
 - Volume Name
 - Volume Source
 - Volume Target

Networks - Display networks attached to the service. It seems the inspect will give you a network ID, then inspecting the network id will give more detail. This can be implemented as a composite query in the backend.

The Network and Volume detail issues need to be clarified

**Comment by FJMentz** [comment]
Adding this to the Card view as well

- [x] ID
- [x] Name
- [x] Image
- [x] Mode
- [x] Replicas
- [x] Last Update
