### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#37]
- [x] ID
- [ ]  Status (Awaiting Task Service to implement)
- [ ] Node (Awaiting Node Service)
- [x] Last Update

**Comment by FJMentz** [comment]
In regards to Node, would you like a nodeID or a node name? Not sure if it is 100% right to assume it has a name.

If we cannot make the assumption we can display the name (if it has one) and of not we display the ID?

**Comment by annamarieHelberg** [comment]
I would prefer the name if we could as no one will ever memorize the node ids of all of their machines. I will look into that

**Comment by egeldenhuys** [comment]
Each node should have a hostname (in most cases) and we should display this. I am not sure how to set the `Spec/Name` value shown in the [API](https://docs.docker.com/engine/api/v1.37/#operation/NodeInspect). For the detailed view we can show the node ID

**Comment by egeldenhuys** [comment]
Closed by #73
