### ISSUE TITLE
Task Detail

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#38]
The same as the list. Perhaps not required

- [x] ID
- [x] Status
- [x] NodeID (as specified in #37)
- [x] Created
- [x] View Logs (as mentioned in #42)

**Comment by FJMentz** [comment]
Just a note that the implementation of how to get the data is the same as #37, this issue is more focused on displaying it for an individual task.

**Comment by FJMentz** [comment]
Was completed in PR #79 👍
