### ISSUE TITLE
Task Operations

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#42]
- [ ] View Logs

**Comment by FJMentz** [comment]
Can we link this to #38 ? Then the log will displayed along with the details of the specified Task?

**Comment by annamarieHelberg** [comment]
I think that can work. How will we implement it though? I am sure the log will be longer than a single line

**Comment by FJMentz** [comment]
Accordion maybe? I see TaskLog only returns a string (no idea how long and what it contains). Will have to go test and see how much/what it actually gives.

**Comment by annamarieHelberg** [comment]
We can do the accordion in the other one. We can also do a modal type thing if someone is up to it

**Comment by FJMentz** [comment]
Was thinking to put the Detail (#38) in a modal and the have the logs in that modal as a Accordion or something.

**Comment by egeldenhuys** [comment]
> Accordion maybe? I see TaskLog only returns a string (no idea how long and what it contains). Will have to go test and see how much/what it actually gives.

@FJMentz , the string returned will be the entire log file, it could easily be a couple of MB

**Comment by FJMentz** [comment]
@egeldenhuys, Do you maybe know the structure of this log file/string? It would be good to know that each entry for example is separated by a semi-colon or a newline character. I've looked around a bit but could not find an example.

**Comment by CDuPlooy** [comment]
See the section on getting tasks logs in the docker engine API. 

I don't think the return value will be very structured or predictably structured at all.

**Comment by FJMentz** [comment]
I have a probably crazy stupid suggestion: 

Can we maybe, instead of trying to display an unstructured string that can by very long or very short, rather provide it to the user as a text-file they download? (No idea how possible or how stupid this is, just putting it out there)

**Comment by CDuPlooy** [comment]
@FJMentz I was thinking the same thing. 

The api does mention journald or json-file drivers. We can have a look at this once we don't have to use the mock api anymore.

**Comment by egeldenhuys** [comment]
> @egeldenhuys, Do you maybe know the structure of this log file/string? It would be good to know that each entry for example is separated by a semi-colon or a newline character. I've looked around a bit but could not find an example.

@FJMentz , the contents of the log depends on the application, it could be a structured nginx log, or debug output from the application. For example `[INFO] Starting docks v0.0.1...\n[ERR] Please mount the docker socket\nThis is probably not an error with npm\n172.17.0.1 - - [28/Apr/2018:19:01:01 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0" "-"`

I did however notice some binary in the output in the actual return string

From my perspective it would be inconvenient to have to download the log file or part of it to view it.

**Comment by FJMentz** [comment]
@egeldenhuys, would it suit you then if we basicaly have a textarea and chuck the log (as we get it from the api) directly in there and also provide the functionality to download it as a text-file (for the users that prefer to have a log they can open in their own text-viewer)?

**Comment by egeldenhuys** [comment]
Throwing the string as received from the API into a read only text area  of reasonable width and height is good. A download feature will also be convienient

**Comment by FJMentz** [comment]
With your permission (@egeldenhuys) I would then add this to the details-view of a task (thus linking it to #38).

**Comment by egeldenhuys** [comment]
> With your permission (@egeldenhuys) I would then add this to the details-view of a task (thus linking it to #38).
@FJMentz , sounds good
