### ISSUE TITLE
View and manage Networks and Volumes

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#57]
Docks should be able to view and manage Networks and services as with the CLI

**Comment by CDuPlooy** [comment]
CreateVolume is not currently working. See https://github.com/TripleParity/docks-api/issues/34

**Comment by egeldenhuys** [comment]
TripleParity/docks-api#34 has been fixed

**Comment by CDuPlooy** [comment]
I was really hoping for something fancy like a popup notification below my reference to indicate that the issue was closed. Colour me sad.

:cry:

**Comment by egeldenhuys** [comment]
The best I could do :laughing:
