### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#58]
Should send details to backend and store auth token

**Comment by FJMentz** [comment]
For demo 3 this will be the only authentication.

**Comment by egeldenhuys** [comment]
@FJMentz, Do you mean the JWT token will not be sent for other requests to the Docks API?

**Comment by FJMentz** [comment]
As far as I remember this is what we discussed today? I might have understood wrong? @egeldenhuys

**Comment by egeldenhuys** [comment]
If all API requests are implemented in a service(s) then the changes should be minor. I will review again once the Docks API fully supports authentication using JWT

**Comment by annamarieHelberg** [comment]
Check the loginPage commit. My comment describes why I assigned you both. I didn't state this but @CDuPlooy and I will do the authentication as soon as the backend has implemented it

**Comment by egeldenhuys** [comment]
Commit and message is [here](https://github.com/TripleParity/docks-ui/commit/9835155d18c2f0c8a23e3958d2fb9c102c2e777c)

**Comment by FJMentz** [comment]
Thank you @annamarieHelberg and @CDuPlooy for taking this :D

**Comment by annamarieHelberg** [comment]
We need you guys to design the page though 😅

**Comment by CDuPlooy** [comment]
An example of logging in and acquiring a jwt.

````js
    this.auth.getToken('admin', 'admin').subscribe(() => {
        console.log(this.token.getToken('auth'));
    }, err => console.log(err));
````

If the second function is called an error has occurred and you'll need to notify the user. If the first anonymous function is fired then you have acquired a jwt. It will be automatically appended to all subsequent http requests.

**Comment by egeldenhuys** [comment]
Thank you @Paulo-W  for your [design](https://docs.google.com/drawings/d/1XJFttNo3SORSK9GYXTi-pXECP9GcauVBgQ41TistYs4/edit). I have made a colour neutral design that more accurately reflects the login page requirements. 

![login-page-1](https://user-images.githubusercontent.com/5778739/41191326-08520e08-6bee-11e8-98a1-ff565c444a54.png)

**Comment by ghost** [comment]
I feel the red bar should appear above the log in button instead. 
The reason for this is it creates a friendlier UI. If the user happens to type in inaccurate features, their current attention or field of view is focused directly on the "Login" button. If the red bar appears directly above it they know they can associate it to their current action. 
Also "Docks on GitHub", directly under log in might confuse some users by implying that they may be able to Login with their git account information, maybe place it somewhere else, such as below the title or bottom right corner perhaps.

**Comment by egeldenhuys** [comment]
The GitHub icon below the login button also tricked me into thinking it is "Login with GitHub".

![login-page](https://user-images.githubusercontent.com/5778739/41240476-dfe660dc-6d9a-11e8-8168-14fb24fe900a.png)

[GitHub Corners](https://github.com/tholman/github-corners)

**Comment by ghost** [comment]
Very nice
