### ISSUE TITLE
Work on Tasks and viewing them for the first sprint

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#62]
My job for this sprint was to view and implement all of the container operations but as we are not going to do that anymore should I implement the task view / operations instead? That was scheduled for sprint 2?

**Comment by egeldenhuys** [comment]
I have now also moved the Task related issues to Sprint 1, @FJMentz can you please facilitate assigning responsibilities for #56 

It would be good if you can also work on an issue in the #56 Epic

**Comment by FJMentz** [comment]
Will do so as soon as I get to my laptop👍🏻
