### ISSUE TITLE
Address of Docks API

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#64]
The browser needs to know the address of the docks API server.

Since we serve static files, it has to be configured using the web interface and then stored for future sessions.

This should be done on the login screen. We can default to docks.currentdomain.com or the IP address in the URL bar.

An alternative is to use environmental variables for the docks-ui container and have a script run when it starts to write the address to some file. The browser can then request this file to configure the address. This way all docks-ui served from that server will have the same address configured.

**Comment by FJMentz** [comment]
@CDuPlooy, will you have a look at this, if you haven't already 😅

**Comment by CDuPlooy** [comment]
The configuration service is used as a central point to change , well configuration.

We can do 

````
this.conf.setApiHostname('http://1.1.1.1:53')
````

At which point all of the API calls will use that as the new location of the API. This could be done in login component - I'll see if I can find a way to use the ip address in the url bar by default for demo sessions.

**Comment by egeldenhuys** [comment]
@devosray has a different view to the architecture in this regard.

**Comment by egeldenhuys** [comment]
I did some work on this in [docks-api-address-#64](https://github.com/TripleParity/docks-ui/compare/docks-api-address-%2364), however my code assumes Docks API is running, and crashes on Travis.

**Comment by egeldenhuys** [comment]
Also note that when deploying in a swarm `localhost` has to be replaced with `127.0.0.1`
