### ISSUE TITLE
Navbar revamp

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#65]
I want to redo the navbar, will create a branch for it and get everyone's input and feedback and then we can decide if we want to continue it like this or rather stay with the navbar as is.

**Comment by egeldenhuys** [comment]
How does your design compare to the current design?
[Screen Designs on Google Drive](https://drive.google.com/drive/folders/12N5U8m1kqp8araVw38xcSJrDwJq-omEK)

Can you make us a model so we can discuss it before implementing?

**Comment by FJMentz** [comment]
@egeldenhuys, Currently it is full of example list items, but does kinda correspond to the screen designs.

Just want to get feedback on this before I start adding more detail and styling.

See this image:
<img width="1680" alt="screen shot 2018-04-27 at 13 05 57" src="https://user-images.githubusercontent.com/17801831/39359803-c1b447c0-4a1b-11e8-9fe8-d1c5e1126e66.png">

**Comment by FJMentz** [comment]
I pushed to branch NavbarRevamp_36... Only noticed now that the issue number on that branch is very very wrong... is there a way to rename a branch? @egeldenhuys 

Or should I rather just create a new branch and delete this one?

**Comment by egeldenhuys** [comment]
To rename a branch just create a new branch from the HEAD of your old branch with a different name

**Comment by egeldenhuys** [comment]
That sidebar looks good :+1:
