### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#66]
So as mentioned long ago by @devosray we might need to look into a logo. I have some ideas, but don't have nearly enough skill to illustrate this. I know someone that wouldn't mind designing a logo for us, but we need to give her ideas so that she can design something for us.

Can everyone that wants to, help think of a cool design that we as a team can look at and then when we come to an agreement on one of them, let it be made?

**Comment by ggcarlosr** [comment]
Hello, I am available to help create a logo that identifies them. what are your requirements

**Comment by CDuPlooy** [comment]
Thank you so much for offering to help with the logo. @FJMentz has someone who is already looking at this if I'm not mistaken, but I'll ask him to reply to this.

**Comment by FJMentz** [comment]
Ah yes, Sorry for only replying now @ggcarlosr. Had a hectic week at university and forgot to reply. Unfortunately we have already found someone to look into this. Thank you for the offer though😄

**Comment by ggcarlosr** [comment]
Hello friend, I have seen that you have reopened the logo application issues, I am interested in helping, what would be the requirements you need for the image that represents them.

**Comment by FJMentz** [comment]
Hi @ggcarlosr, as mentioned before, we unfortunately already found someone to design the logo😅, I only opened the issue to link to the PR. Once again thank you for the offer!
