### ISSUE TITLE
Navigation between pages

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#67]
It has been discussed that the basic navigation will include the different views, managing stacks/services/tasks and adding stacks/services/tasks. The navigation can be reduced to the basic views and from the view page navigation to the add or manage page. However, I feel that this approach should be avoided as the extra navigation can become tedious and cumbersome. A better approach would be to have all of the pages accessible through the navbar. Your input on how to approach this will be greatly appreciated. If you can think of another approach that will be helpful too. Also, if you can think of other pages that need to be included in the navigation please comment so.

**Comment by FJMentz** [comment]
I agree that we should try to keep the navigation on the navbar as simple as possible (so one click -> page changes).

Also me and @CDuPlooy were discussing the fact that we should try to make routing só that a power-user can get to a specific desired page just by using the 'url'.

**Comment by egeldenhuys** [comment]
What I would like to see is a list of pages and the functions they will provide as well as the URL to access that page. The goal is to see which functions map to which pages.

Example:
- `/` - Landing page. Shows dashboard of current Swarm State
- `/stacks` - Shows stacks. Can filter and sort to find a stack. Can click on stack to go to `/stacks/<name>`
- `/stacks/<name>` - Show `inspect` output for the given stack
- `/stacks/create` - Interface to create a new stack

**Comment by egeldenhuys** [comment]
> Also me and CDuPlooy were discussing the fact that we should try to make routing só that a power-user can get to a specific desired page just by using the 'url'.

Implemented by #74

**Comment by egeldenhuys** [comment]
@annamarieHelberg, my question put differently: What items do you suggest placing in the navbar?

**Comment by annamarieHelberg** [comment]
I suggest we link to every page. For example, task view and the detail view as well. 

My only concern is that it will not be well received if the user (a.k.a. Compiax) have to go to a task page, then to the lost view page and then lastly to the details page to look at the details of the tasks. A direct navigation to that page will be preferred.

**Comment by ghost** [comment]
@annamarieHelberg and everyone else I realise we will be discussing this come thursday but there are a couple things I would like to bring up about this in the meantime.

1. speaking from previous mistakes I made last year flooding the user 
with information in the navbar is never a good idea and although it may 
seem like its really intuitive and simple to use dropdowns in navbars 
its proven to be more ineffective than helpful. They are not user freindly and 
are come off more as clunky and annoying. 
2. I dont see the need of being able to directly link to a details 
page as one can only find out details of a selected task/service/volume etc. 
3. I do not understand why in your example the user needs to go to tasks then 
listview then details, would things like the viewing not be set up 
automatically as in when the user clicks on "tasks" they will see a 
list view and they can then change it to a card view etc by the use of a button?
4. I do like your idea of giving the user faster access to pages and 
therefore would like to suggest some ideas as well.
  - It is a good practice to give the user multiple access point to 
  the same webpage so we can have the different "view" pages as 
  dropdowns as you suggested but we may consider also providing 
  them with buttons to change view somewhere within the page as well
  - I do not agree with pages that immediatly load details, 
  removes, and managing functionality as you need to select 
  a task/service... before you can perform these operations 
  on it. but I agree we can have a link to a page where you 
  can add a task/service... as this would provide quick access
   for the user. Might I suggest though that we place this 
   link outside the side nav perhaps as a permanent link in the 
   head nav or as buttons on the users home page just to give the user a
   multiple access points to this page. 
  - I strongly recomend we keep the side nav as simple as possible so 
  I agree we need to have every one of task/service.. page links accessible via the 
  nav but am not sure why it would not be like that as it was implemented this
   way in screen designs as well.

**Comment by FJMentz** [comment]
Make note of the following:

>2 I dont see the need of being able to directly link to a details
page as one can only find out details of a selected task/service/volume etc.
- There will not be a direct link to the details view. This will be accessed from the cards view


>3 I do not understand why in your example the user needs to go to tasks then
listview then details, would things like the viewing not be set up
automatically as in when the user clicks on "tasks" they will see a
list view and they can then change it to a card view etc by the use of a button?
- This was semi-discussed in yesterday's meeting and will further be discussed in the meeting as stated on the group.


>I do not agree with pages that immediatly load details,
removes, and managing functionality as you need to select
a task/service... before you can perform these operations
on it. 
- The plan is not to have pages for remove/managing of task/services/xxx, but rather to provide this functionality from the different view-pages (as you say, since it is linked to a specific task/service/xxxx

>Might I suggest though that we place this
link outside the side nav perhaps as a permanent link in the
head nav or as buttons on the users home page just to give the user a
multiple access points to this page.
- @Paulo-W, why would you not want it in the navbar? Isn't that the constant thing that gives you the easiest access to this? Also I don't think we've planned for a homepage other than the welcome page mentioned in [an open issue](https://github.com/TripleParity/docks-ui/issues/70)

**Comment by ghost** [comment]
We can talk about it come thursday, if you semi spoke about alternative plans I am sorry but as for your first statement you are contradicting the comment above mine so we can talk about it Thursday

**Comment by FJMentz** [comment]
Just leaving this here for the discussion:

<img width="619" alt="screen shot 2018-05-01 at 19 40 11" src="https://user-images.githubusercontent.com/17801831/39485000-c73e4948-4d77-11e8-892a-6475d61d9b4b.png">

**Comment by ghost** [comment]
I have uploaded a folder to screen designs called idea 1 available via google drive 
(https://drive.google.com/drive/folders/1wBfqMUDN_5yx_vSul9rqmPTQGR1cjwo4)

This goes over the first idea discussed in todays meeting I will upload the next one soon please go over it and let me know if there is anyhing you would like to add.

**Comment by ghost** [comment]
Also ideas 2 have now been added as well I will finalize idea 4 tomorrow you can find all on the drive.

**Comment by FJMentz** [comment]
The layer in idea2 dropdownselecting is a bit off, also please add a space between he dropdown and side bar.

**Comment by FJMentz** [comment]
Referencing your idea 1, you need more levels of sub menus eg Task->views.

Also a thing we all agree on is not choosing a <item> to perform an operation on on a general page. This will be implemented as: from a view you click on an item and it takes you to the operations page for that button.

**Comment by annamarieHelberg** [comment]
I agree with Francois with that after clicking on a certain service (or whatever) it will take you to a page where the operations can be executed on that specific service (or whatever). So it shouldn't be in the navbar. 

The rest looks really nice

**Comment by ghost** [comment]
I agree with you guys just implemented the ideas discussed in meeting. I will update the nav bar now.

**Comment by FJMentz** [comment]
I have looked at the designs and here is my feedback so far:

- Idea 1 is still not complete (sub-menus haven't been added)

- I like the idea of having the dropdown in the list view [in idea 3](https://docs.google.com/drawings/d/1Z7llBkNhHvFC7ShABr58UvpAsw7vIPehqgBXkxvSla0/edit) if it would take you to the correct tab in the operations view [in idea 4](https://docs.google.com/drawings/d/16q3J9mNluWmw7Vc1UEV8mMY1TAqJMDKaNgaMisE38c0/edit)

As soon as we have idea 1 correct, we will ask input from Compiax.

**Comment by ghost** [comment]
@FJMentz I did not change Idea 1 as I saw no purpose. It has been discused and stated here that we will not have a direct link to any of the operations pages so taking out the operations in the nav bar leaves you with just the views this would result in sub-menues as follows 
task
   -> views
       ->list
       ->card ....

there is no point of this. Furthermore I have been busy with the card designs as per your request and I feel my time is better spent working on the stuff that we will be able to present in our demo. The files  have been shaired in google drive so if you really feel that the sub menues must be added you are welcome to change them.

**Comment by FJMentz** [comment]
@Paulo-W that is not what I mentioned that needed to change. However due to reasons I will now be taking over this issue. Will give update soon.

**Comment by FJMentz** [comment]
This was discussed with Jason this afternoon and he gave us a clear-ish indication of how to go about this. I will show/explain to everyone as I see you in person. For now this is the list of people that know:

- [x] Francois
- [x] Evert
- [x] Paul
- [ ] Armand
- [ ] Anna Marié

I will start implementing it from tomorrow.

**Comment by FJMentz** [comment]
Didn't mean to close that before it was actually implemented... oops 😨

**Comment by egeldenhuys** [comment]
My view of how the pages should connect to each other:

![pages](https://user-images.githubusercontent.com/5778739/42077498-6b1f553c-7b79-11e8-9a24-ad7a7680f42e.png)

[View UML source file](https://github.com/TripleParity/docks/tree/requirements-design/docs)
