### ISSUE TITLE
Task name

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#69]
I've been playing a lot with the api and noticed that in the example for listTasks the one Task has a name attribute and the other doesn't.

Can we make the assumption that most of our tasks will have a name and the minority won't? Or is this a far fetched assumption?

**Comment by FJMentz** [comment]
As mentioned in #37, if we cannot make the assumption, we can display the name (if it has one) and of not we display the ID?

**Comment by egeldenhuys** [comment]
The hostname attribute should be present in most cases, so if there is no name and no hostname then we can display the ID, or a concatenated version of it

**Comment by FJMentz** [comment]
As it is implemented now, we look for a name, and if not present we use a concatenated version of the ID (concatenated to 6 characters) prepended by 'ID: ' to clarify that it is not the name of the Task.

I'm not exactly sure what you mean by a hostname (or rather I cannot find anything referring to that from the [API page](https://docs.docker.com/engine/api/v1.37/#operation/TaskList)). Can you maybe explain this in the meeting today @egeldenhuys?
