### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#70]
I'm going to work on a welcome page that's basically just going to be a page that welcomes the User to the system and give advice on where to find what. This will act as a 'home page' which the user will see as soon as they logged in.

Any comments on this?

**Comment by egeldenhuys** [comment]
It would be nice to have a welcome screen or some type of help in the system. As a user of the system I would expect it to give me an overview of the features and where to find them, as well as explanation to any new concepts introduced.

**Comment by FJMentz** [comment]
Every time a new concept is included, do we just prepend it to the page as a 'patch note' or would you prefer a section on the page just for new updates that gets overwritten every-time a new concept is released?

Scenario 1:

Welcome message
Basic concepts
Newest patchnote
List of older patch-notes (desc)

Scenario 2:

Welcome message
Basic Concepts
Latest patch-note

**Comment by egeldenhuys** [comment]
For the "patch notes" we can direct the user to the `CHANGELOG.md` which will be introduced later.

An alternative to a welcome screen is to have question mark icons next to headings or actions to give a brief explanation.

**Comment by egeldenhuys** [comment]
Are we going to replace this page with the Graph page?

**Comment by FJMentz** [comment]
@egeldenhuys I think that is an excellent idea!

**Comment by egeldenhuys** [comment]
Replaced by #75
