### ISSUE TITLE
Information the graph page must display.

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#75]
Hi guys. The graph code is up and running. I just want your input in what you would like graph to display. I looked at what Portainer does and we can follow a similar approach but I would like your opinions as well. Also, I think we should put the graph view on a separate page as that will just simplify some logic.

**Comment by FJMentz** [comment]
Which branch is this done on?

**Comment by annamarieHelberg** [comment]
I created a new branch (graphs). I pushed it now

**Comment by egeldenhuys** [comment]
A useful summary would be
- Number of Nodes in the swarm
- Number of services in the swarm
- Number of tasks in the swarm
- Total RAM of swarm

There might be more useful metrics that I did not mention

**Comment by CDuPlooy** [comment]
This will be closed when #183 is closed (@annamarieHelberg is commenting from @CDuPlooy  account)

**Comment by egeldenhuys** [comment]
Closed by https://github.com/TripleParity/docks-ui/pull/185
