### ISSUE TITLE
Build and test on Travis CI

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#8]
The Docker Hub builds are failing, would be nice to see that in Travis

**Comment by CDuPlooy** [comment]
How would you go about that?

As done in [docks](https://github.com/TripleParity/docks/blob/travis-ci-build-docker-%235/.travis.yml)?

**Comment by egeldenhuys** [comment]
The Docks travis.yml is outdated. We only need to build the Angular app on Travis.

Something like:
```
language: node_js
node_js:
  - "701.782" # Whatever it is these days

before_script:
  - npm install

script:
  - ng build
```
Source: https://houssein.me/continuous-integration-angular-firebase-travisci

**Comment by CDuPlooy** [comment]
Builds are now passing for the bootstrap_migration branch.
Builds will fail if files do not pass linting or any of the angular tests defined in *.spec.ts fail. May I close this?
