### ISSUE TITLE
Simple swarm creation script

### ISSUE THREAD

**Issue by devosray** [TripleParity/docks-ui#80]
There is a need for a simple script that will create a simple swarm for development purposes.

**Comment by egeldenhuys** [comment]
My docker machine is having problems assigning IPs to the created virtual machines

**Comment by FJMentz** [comment]
@devosray, Just a question, for Demo purposes, will we use the same script? Also for the demo, can we maybe add a service that has logs (nginx doesn't seem to have any) to show that the logs actually do work?
