### ISSUE TITLE
Filter and list Containers

### ISSUE THREAD

**Issue by CDuPlooy** [TripleParity/docks-ui#9]
We can use this for

* Search ( With additional query parameters )
* Listing containers

See the [docker engine API](https://docs.docker.com/engine/api/v1.37/#tag/Container); Additionally the current getContainers function should be modified to work with the query parameters.

**Comment by FJMentz** [comment]
Do we want to query the back-end for the search? feels unnecessary  if we already have the containers in some data structure? @CDuPlooy

**Comment by CDuPlooy** [comment]
Looking at the API provided by docker we should be able to set a filter on containers for the request. We thus only need to make one query to the backend or maybe a few on every other few keystrokes. I suggest we use ``Observable.debounceTime(x).subscribe()``
