### ISSUE TITLE
Obtain and display username from backend

### ISSUE THREAD

**Issue by devosray** [TripleParity/docks-ui#92]
Currently, a placeholder name is used instead of the name of the user. Until the backend implements the required functionality, a different placeholder must be used.

**Comment by egeldenhuys** [comment]
The JWT should contain the username, will this be sufficient?

**Comment by egeldenhuys** [comment]
Closing as the front-end should have sent the username in the first place. Also to communicate with Docks API, a JWT is required that will contain the username.
